### ISSUE TITLE
Move to ZenHub boards

### ISSUE THREAD

**Issue by brucellino** [AAROC/CODE-RADE#104]
To move to Zenhub, we need to add the repos to the board.

**Comment by brucellino** [comment]
- [ ] autodock-deploy
- [ ] abyss-deploy
- [ ] wrf-deploy
- [ ] gcc-deploy
- [ ] netcdf-deploy
- [ ] weka-deploy
- [ ] matlab-runtime-deploy
- [ ] java-openjdk-deploy
- [ ] GADGET-deploy
- [ ] abinit-deploy
- [ ] root-deploy
- [ ] gsl-deploy
- [ ] numpy-deploy
- [ ] python-deploy
- [ ] libxml2-deploy
- [ ] gromacs-deploy
- [ ] fftw3-deploy
- [ ] quantum-espresso-deploy
- [ ] lapack-deploy
- [ ] readline-deploy
- [ ] rlang-deploy
- [ ] hmmer-deploy
- [ ] OpenMPI-deploy
- [ ] gmp-deploy
- [ ] clhep-deploy
- [ ] pythia8-deploy
- [ ] openssl-deploy
- [ ] emboss-deploy
- [ ] add-scores-deploy
- [ ] impute-deploy
- [ ] shapeit-deploy
- [ ] htk-deploy
- [ ] libsvm-deploy
- [ ] gnuplot-deploy
- [ ] plink-deploy
- [ ] llvm-deploy
- [ ] gnutls-deploy
- [ ] lua-deploy
- [ ] gdal-deploy
- [ ] proj-deploy
- [ ] oases-deploy
- [ ] velvet-deploy
- [ ] sparsehash-deploy
- [ ] hdf5-deploy
- [ ] fitsio-deploy
- [ ] mpich-deploy
- [ ] heasoft-deploy
- [ ] jasper-deploy
- [ ] freetype-deploy
- [ ] fftw2-deploy
- [ ] scalapack-deploy
- [ ] zlib-deploy
- [ ] Sympy-deploy
- [ ] suitesparse-deploy
- [ ] sqlite-deploy
- [ ] tcltk-deploy
- [ ] scipy-deploy
- [ ] sage-deploy
- [ ] repast-deploy
- [ ] Pandas-deploy
- [ ] ncurses-deploy
- [ ] OpenFOAM-deploy
- [ ] openblas-deploy
- [ ] modules-deploy
- [ ] mpc-deploy
- [ ] mpfr-deploy
- [ ] libpng-deploy
- [ ] matplotlib-deploy
- [ ] IMA2-deploy
- [ ] bzlib-deploy

**Comment by brucellino** [comment]
Scratch this... They done closed https://github.com/waffleio/waffle.io/issues/806
